cc_binary(
  name = "core",
  srcs = ["main.cpp"],
  deps = ["@com_google_nearby//connections:core", 
          "@com_google_nearby//connections:core_types",
        "@com_google_nearby//connections/implementation:internal",
        "@com_google_nearby//internal/platform:base",
          "@com_google_nearby//internal/platform:logging",
        "@com_google_nearby//internal/platform:types",
  ]


)
